### ISSUE TITLE
Question: why remove `description` from the index?

### ISSUE THREAD

**Issue by eturino** [galdiuz/nethys-search#5]
I see that `description` was removed from the index in https://github.com/galdiuz/nethys-search/commit/017e3e15b3a404c108dded7be52a817922666a7a 
I wonder if there is a specific reason for it, or if we could get it back.

**Comment by galdiuz** [comment]
The commit you linked only removed the mapping, and it did so because the field was not used. It actually stopped being used as early as https://github.com/galdiuz/nethys-search/commit/95367227346bd84269eec43ddacdc83171f7bbb0. The reason for its removal was that I initially attempted to (poorly) parse descriptions because I thought I would need it for searching, but then realized that I could get better search results by getting the text of the entire node instead. Thus the `description`-field was replaced by the `text`-field.

Because I have no intention to display the description in search results there is no need to try to parse it, so I will not attempt to bring it back.

**Comment by eturino** [comment]
I get it now, thanks!
